src/model/Noticia.java
package model;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Noticia {
	
	private int not_id;
	private String not_titulo;
	private String not_descricao;
	private String not_keywords;
	private byte[] not_imgdest;
	private String not_autor;
	private String not_texto;
	private Date not_data;
	private int user_id;
	
	public int getNot_id() {
		return not_id;
	}
	public void setNot_id(int not_id) {
		this.not_id = not_id;
	}
	public String getNot_titulo() {
		return not_titulo;
	}
	public void setNot_titulo(String not_titulo) {
		this.not_titulo = not_titulo;
	}
	public String getNot_descricao() {
		return not_descricao;
	}
	public void setNot_descricao(String not_descricao) {
		this.not_descricao = not_descricao;
	}
	public String getNot_keywords() {
		return not_keywords;
	}
	public void setNot_keywords(String not_keywords) {
		this.not_keywords = not_keywords;
	}
	public byte[] getNot_imgdest() {
		return not_imgdest;
	}
	public void setNot_imgdest(byte[] not_imgdest) {
		this.not_imgdest = not_imgdest;
	}
	public String getNot_autor() {
		return not_autor;
	}
	public void setNot_autor(String not_autor) {
		this.not_autor = not_autor;
	}
	public String getNot_texto() {
		return not_texto;
	}
	public void setNot_texto(String not_texto) {
		this.not_texto = not_texto;
	}	
	public String getNot_data() {
		DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return dateFormat.format(not_data);
	}
	
	public String getDataFormatada() {
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		return dateFormat.format(not_data);
	}
	
	public String getHoraFormatada() {
		DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
		return dateFormat.format(not_data);
	}
	
	public String getDataHoraFormatada() {
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
		return dateFormat.format(not_data);
	}	
	
	public void setNot_data(Date not_data) {
		this.not_data = not_data;
	}
	public int getUser_id() {
		return user_id;
	}
	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}

}

src/model/dao/DaoBanner.java
package model.dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import model.Banner;
import model.db.ConnectionFactory;

public class DaoBanner {
	
	public Banner getBan(String ban_id){
		
		Banner banner = null;
		
		try{
			
			Connection con = ConnectionFactory.createConnection();
			String sql ="SELECT * FROM banner WHERE ban_id = ?";  
			PreparedStatement st = con.prepareStatement(sql);
			st.setString(1, ban_id);
			ResultSet rs = st.executeQuery();
			
			if(rs.next()){			
				
				banner = new Banner();
				banner.setBan_id(rs.getInt("ban_id"));
				banner.setBan_nome(rs.getString("ban_nome"));
				banner.setBan_descricao(rs.getString("ban_descricao"));
					
			}
			
			st.close();
			con.close();
			
			} catch (SQLException e){
				
				e.printStackTrace();
				
			}	
		
			return banner;
			
	}
			
	public Banner getBanById (int id){		// getbanner by ID (pega banner e suas informacoes da tabela)
		
		Banner banner = null;
		
		try{
			
			Connection con = ConnectionFactory.createConnection();
			String sql ="SELECT * FROM banner WHERE ban_id = ?";  
			PreparedStatement st = con.prepareStatement(sql);
			st.setInt(1, id);
			ResultSet rs = st.executeQuery();
			
			if(rs.next()){
				
				banner = new Banner();
				banner.setBan_id(rs.getInt("ban_id"));
				banner.setBan_nome(rs.getString("ban_nome"));
				banner.setBan_origem(rs.getString("ban_origem"));
				banner.setBan_contato_tel(rs.getString("ban_contato_tel"));
				banner.setBan_contato_site(rs.getString("ban_contato_site"));
				banner.setBan_descricao(rs.getString("ban_descricao"));
				banner.setBan_ultima_atualizacao(rs.getDate("ban_ultima_atualizacao"));
				banner.setBan_publicacao(rs.getString("ban_publicacao"));
				banner.setUser_id(rs.getString("user_id"));
				
			}
			
			st.close();
			con.close();
			
			} catch (SQLException e){
				
				e.printStackTrace();
				
			}	
		
			return banner;
			
	}
		
	public List<Banner> getListBan(){		
		
		List<Banner> listaBanners = new ArrayList<Banner>();
		
		try{
			
			Connection con = ConnectionFactory.createConnection();
			String sql ="SELECT * FROM banner ORDER BY ban_id";  
			PreparedStatement st = con.prepareStatement(sql);
			ResultSet rs = st.executeQuery();
			
			while(rs.next()){
				
				Banner banner = new Banner();
				banner.setBan_id(rs.getInt("ban_id"));
				banner.setBan_nome(rs.getString("ban_nome"));
				banner.setBan_origem(rs.getString("ban_origem"));
				banner.setBan_contato_tel(rs.getString("ban_contato_tel"));
				banner.setBan_contato_site(rs.getString("ban_contato_site"));
				banner.setBan_descricao(rs.getString("ban_descricao"));
				banner.setBan_ultima_atualizacao(rs.getDate("ban_ultima_atualizacao"));
				banner.setBan_publicacao(rs.getString("ban_publicacao"));
				banner.setUser_id(rs.getString("user_id"));
				listaBanners.add(banner);
				
			}
			
			st.close();
			con.close();
			
		} catch (SQLException e){
			
			e.printStackTrace();
			
		}		
		
		return listaBanners;
		
	}
	
public List<Banner> getListBanHome(){		
	
	List<Banner> listaBanners = new ArrayList<Banner>();
	try{
		Connection con = ConnectionFactory.createConnection();
		String sql ="SELECT * FROM banner WHERE ban_publicacao = 1";  
		PreparedStatement st = con.prepareStatement(sql);
		ResultSet rs = st.executeQuery();
		while(rs.next()){
			Banner banner = new Banner();
			banner.setBan_id(rs.getInt("ban_id"));
			banner.setBan_nome(rs.getString("ban_nome"));
			banner.setBan_origem(rs.getString("ban_origem"));
			banner.setBan_contato_tel(rs.getString("ban_contato_tel"));
			banner.setBan_contato_site(rs.getString("ban_contato_site"));
			banner.setBan_descricao(rs.getString("ban_descricao"));
			banner.setBan_ultima_atualizacao(rs.getDate("ban_ultima_atualizacao"));
			banner.setBan_publicacao(rs.getString("ban_publicacao"));
			banner.setUser_id(rs.getString("user_id"));
			listaBanners.add(banner);
		}
		st.close();
		con.close();
	} catch (SQLException e){
		e.printStackTrace();
	}		
	return listaBanners;
}
	
	
	public boolean addBan(Banner banner){
		int added=0;

		try{
			
			Connection con = ConnectionFactory.createConnection();
			String sql ="INSERT INTO banner (ban_nome,ban_origem,ban_contato_tel,ban_contato_site,ban_descricao,ban_ultima_atualizacao,ban_publicacao,ban_imagem,user_id) VALUES (?,?,?,?,?,?,?,?,?)";
			PreparedStatement st = con.prepareStatement(sql);
			st.setString(1, banner.getBan_nome());
			st.setString(2, banner.getBan_origem());
			st.setString(3, banner.getBan_contato_tel());
			st.setString(4, banner.getBan_contato_site());
			st.setString(5, banner.getBan_descricao());
			st.setDate(6, new Date(System.currentTimeMillis()));
			st.setString(7, banner.getBan_publicacao());
			st.setBytes(8, banner.getBan_imagem());
			st.setString(9, banner.getUser_id());
			
			added = st.executeUpdate();
			
			st.close();
			con.close();
			
		} catch (SQLException e){
			
			e.printStackTrace();
			
		}
		return added > 0;
	}	
		
	public int delBan(int ban_id){
		
		int delete=0;		
		try{			
			Connection con = ConnectionFactory.createConnection();
			String sql ="DELETE FROM banner WHERE ban_id=?";  
			PreparedStatement st = con.prepareStatement(sql);
			st.setInt(1, ban_id);		
			delete = st.executeUpdate();
			
			st.close();
			con.close();			
		} catch (SQLException e){		
			e.printStackTrace();			
		}		
		return delete;		
	}
	
	
	public int updtBan(Banner banner){
		
		int update=0;

		try{
			
			Connection con = ConnectionFactory.createConnection();
			String sql ="UPDATE banner SET ban_nome=?, ban_origem=?, ban_contato_tel=?, ban_contato_site=?, ban_descricao=?, ban_ultima_atualizacao=?, ban_publicacao=?, ban_imagem=?, user_id=? WHERE ban_id=?";  
			PreparedStatement st = con.prepareStatement(sql);
			
			st.setString(1, banner.getBan_nome());
			st.setString(2, banner.getBan_origem());
			st.setString(3, banner.getBan_contato_tel());
			st.setString(4, banner.getBan_contato_site());
			st.setString(5, banner.getBan_descricao());
			st.setDate(6, new Date(System.currentTimeMillis()));
			st.setString(7, banner.getBan_publicacao());
			st.setBytes(8, banner.getBan_imagem());
			st.setString(9, banner.getUser_id());
			st.setInt(10, banner.getBan_id());
			
			update = st.executeUpdate();
			
			st.close();
			con.close();
			
		} catch (SQLException e){
			
			e.printStackTrace();
			
		}
		return update;
	}		
	
	
public int updtBanNoPic(Banner banner){
		
		int update=0;
		
		try{
			
			Connection con = ConnectionFactory.createConnection();
			String sql ="UPDATE banner SET ban_nome=?, ban_origem=?, ban_contato_tel=?, ban_contato_site=?, ban_descricao=?, ban_ultima_atualizacao=?, ban_publicacao=?, user_id=? WHERE ban_id=?";  
			PreparedStatement st = con.prepareStatement(sql);
			
			st.setString(1, banner.getBan_nome());
			st.setString(2, banner.getBan_origem());
			st.setString(3, banner.getBan_contato_tel());
			st.setString(4, banner.getBan_contato_site());
			st.setString(5, banner.getBan_descricao());
			st.setDate(6, new Date(System.currentTimeMillis()));
			st.setString(7, banner.getBan_publicacao());
			st.setString(8, banner.getUser_id());
			st.setInt(9, banner.getBan_id());
			
			update = st.executeUpdate();
			
			st.close();
			con.close();
			
		} catch (SQLException e){
			
			e.printStackTrace();
			
		}
		
		
		return update;
	}

}

src/model/dao/FotosDao.java
package model.dao;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import model.db.ConnectionFactory;
import model.Foto;
import model.Utilidade;



public class FotosDao {
	public Foto getFotosById(Long id){
		
		Foto foto = null;
		
		try{
			
			Connection con = ConnectionFactory.createConnection();
			String sql ="SELECT * FROM foto WHERE foto_id = ?";  
			PreparedStatement st = con.prepareStatement(sql);
			st.setLong(1, id);
			ResultSet rs = st.executeQuery();
			
			rs.next();
				
			foto = new Foto();
			foto.setIdFoto(rs.getLong("foto_id"));	
			foto.setTitulo(rs.getString("foto_titulo"));
			foto.setDescricao(rs.getString("foto_descricao"));
			foto.setAlbum(rs.getString("foto_album"));
			//util.setLogotipo(rs.getByte("not_texto"));
			foto.setUsr_id(rs.getInt("usr_id"));
			
			st.close();
			con.close();
			
			} catch (SQLException e){
				
				e.printStackTrace();
				
			}
		
			return foto;
			
	}
	
	
	
	
	
		public boolean add(Foto foto) throws IOException{
			int added=0;
			
			System.out.println(foto.getUsr_id());
			try{
			Connection con = ConnectionFactory.createConnection();
			String sql ="insert into foto (foto_titulo,foto_imagem,foto_descricao,foto_album,usr_id) values (?,?,?,?,?)";  
			PreparedStatement st = con.prepareStatement(sql);		
			st.setString(1,foto.getTitulo());		 
			st.setBytes(2,foto.getImagem());
			st.setString(3,foto.getDescricao());
			st.setString(4,foto.getAlbum());
			
			st.setInt(5, foto.getUsr_id());
			added = st.executeUpdate();
			st.close();
			con.close();		
			} catch (SQLException e){
				e.printStackTrace();
			}		
			return added>0;
		}
		
		public int delete(int idfoto){
			int delete=0;
			try{
			Connection con = ConnectionFactory.createConnection();
			String sql ="Delete from foto where foto_id=?";  
			PreparedStatement st = con.prepareStatement(sql);
			st.setInt(1, idfoto);		
			delete = st.executeUpdate();
			st.close();
			con.close();		
			} catch (SQLException e){
				e.printStackTrace();
			}
			return delete;
		}
		
		public int deleteAlbum(String album){
			int delete=0;
			try{
			Connection con = ConnectionFactory.createConnection();
			String sql ="Delete from foto where foto_album=?";  
			PreparedStatement st = con.prepareStatement(sql);
			st.setString(1, album);		
			delete = st.executeUpdate();
			st.close();
			con.close();		
			} catch (SQLException e){
				e.printStackTrace();
			}
			return delete;
		}
		
		public List<Foto> getConsulta(){		
			List<Foto> fotos = new ArrayList<Foto>();
			try{
			Connection con = ConnectionFactory.createConnection();
			String sql ="Select * from foto";  
			PreparedStatement st = con.prepareStatement(sql);
			ResultSet rs = st.executeQuery();
			while(rs.next()){
				Foto foto = new Foto();
				foto.setIdFoto(rs.getInt("foto_id"));		
				foto.setTitulo(rs.getString("foto_titulo"));		
				foto.setDescricao(rs.getString("foto_descricao"));
				foto.setAlbum(rs.getString("foto_album"));
				fotos.add(foto);
			}		
			st.close();
			con.close();		
			} catch (SQLException e){
				e.printStackTrace();
			}		
			return fotos;
		}
		
		public List<String> getConsultaAlbum(){		
			List<String> albuns = new ArrayList<String>();
			try{
			Connection con = ConnectionFactory.createConnection();
			String sql ="Select DISTINCT foto_album from foto ORDER BY foto_album";  
			PreparedStatement st = con.prepareStatement(sql);
			ResultSet rs = st.executeQuery();
			while(rs.next()){
				String albumNome = rs.getString("foto_album");
				albuns.add(albumNome);
			}		
			st.close();
			con.close();		
			} catch (SQLException e){
				e.printStackTrace();
			}		
			return albuns;
		}
		
		public List<Foto> getConsultaFotosPorAlbum(String album){		
			List<Foto> fotos = new ArrayList<Foto>();
			try{
			Connection con = ConnectionFactory.createConnection();
			String sql ="Select * from foto where foto_album = ?";  
			PreparedStatement st = con.prepareStatement(sql);
			st.setString(1,album);
			ResultSet rs = st.executeQuery();
			
			while(rs.next()){
				Foto foto = new Foto();
				foto.setIdFoto(rs.getInt("foto_id"));		
				foto.setTitulo(rs.getString("foto_titulo"));		
				foto.setDescricao(rs.getString("foto_descricao"));
				foto.setAlbum(rs.getString("foto_album"));
				fotos.add(foto);
			}		
			st.close();
			con.close();		
			} catch (SQLException e){
				e.printStackTrace();
			}		
			return fotos;
		}
		
		
		public boolean update(Foto foto) throws IOException{
			int update=0;
			try{
			Connection con = ConnectionFactory.createConnection();
			String sql ="UPDATE foto SET foto_titulo=?,foto_descricao=?,foto_album=?,usr_id=? where foto_id=? ";  
			PreparedStatement st = con.prepareStatement(sql);		
			st.setString(1, foto.getTitulo());					 	
			st.setString(2, foto.getDescricao());
			st.setString(3, foto.getAlbum());			
			st.setInt(4, foto.getUsr_id());
			st.setLong(5, foto.getIdFoto());		
			update = st.executeUpdate();
			st.close();
			con.close();		
			} catch (SQLException e){
				e.printStackTrace();
			}		
			return update>0;
		}
	}

src/controller/eventos/ExcluirEventoServlet.java
package controller.eventos;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.dao.EventosDao;

public class ExcluirEventoServlet extends HttpServlet{
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
		throws ServletException, IOException {
		EventosDao dao = new EventosDao();
		int idEvento =Integer.parseInt(req.getParameter("id"));
		dao.delete(idEvento);
		resp.sendRedirect("index.jsp?pag=eventosConsulta");

	}
}

src/controller/eventos/ExibirEventoServlet.java
package controller.eventos;

import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.db.ConnectionFactory;
import org.apache.tomcat.util.http.fileupload.FileItem;

public class ExibirEventoServlet extends HttpServlet {
	 protected void processRequest(HttpServletRequest request, HttpServletResponse response)
			    throws ServletException, IOException {			        			        
			        try {			 
			        	int id = Integer.parseInt(request.getParameter("id"));			        	
			        	Connection con = ConnectionFactory.createConnection();
			            PreparedStatement ps = con.prepareStatement("select evt_imagem from eventos where evt_idEventos=?");			            			            			            
			            ps.setInt(1, id);
			            ResultSet rs = ps.executeQuery();
			            rs.next();			            			            	            		
			            byte[] arquivo = rs.getBytes(1);
			            response.setContentType("image/jpeg");			          
			            OutputStream os = response.getOutputStream();			           			            
			            os.write(arquivo);	
			            os.close();			            			            
			        }
			        catch(Exception ex) {
			             System.out.println(ex.getMessage());
			        }
			    } 

			    @Override
			    protected void doGet(HttpServletRequest request, HttpServletResponse response)
			    throws ServletException, IOException {
			        processRequest(request, response);
			    } 
			    @Override
			    protected void doPost(HttpServletRequest request, HttpServletResponse response)
			    throws ServletException, IOException {
			        processRequest(request, response);
			    }			
}

WebContent/cabecalho.jsp
<div id="cabecalho">
	<a href="index.jsp"><img src="imagens/logoPrincipal.jpg" border="0px"/></a>
</div>

<div id="navbar">
	<div id="navbarBusca">
		<form id="formBusca" method="get" action="noticiaBusca.do">
			<input type="submit" value="Buscar" class="Botao" />  
			<input type="text" name="palavra" class="Campo" />
		</form>
	</div>
	
	<div id="navbarIcons">
		<a href="http://www.facebook.com/pages/Pindoretama/112618832084319"><img src="imagens/social/facebook.png" border="0" /></a>
		<a href="http://www.twitter.com/pindoretama"><img src="imagens/social/twitter.png" border="0" /></a>
		<a href="http://www.youtube.com/user/pindoretamavideos?feature=mhee"><img src="imagens/social/youtube.png" border="0" /></a>
	</div>	
	
</div>

WebContent/eventosVisCompleta.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt"%>

<h1>Eventos</h1>

<jsp:useBean id="eventos" class="model.dao.EventosDao" scope="page"/>
<c:forEach var="evento" items="${eventos.consulta}">
	<c:if test="${evento.idEvento eq param.id}">
		<h2>${evento.titulo}</h2>
		<p><img src="exibirEvento.do?id=${param.id}" style="float:right; margin-left: 10px;" width="200" >
		${evento.descricao}
		</p>
	</c:if>
</c:forEach>  	

WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"
    import="java.util.*, java.io.*" %>
    
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>    


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>SWIM</title>
<link href="estilos/principal.css" rel="stylesheet" type="text/css" />
<!-- Attach our CSS -->
	  	<link rel="stylesheet" href="estilos/orbit-1.2.3.css">
	  	
		<!-- Attach necessary JS -->
		<script type="text/javascript" src="slider/jquery-1.5.1.min.js"></script>
		<script type="text/javascript" src="slider/jquery.orbit-1.2.3.min.js"></script>	
		
			<!--[if IE]>
			     <style type="text/css">
			         .timer { display: none !important; }
			         div.caption { background:transparent; filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000,endColorstr=#99000000);zoom: 1; }
			    </style>
			<![endif]-->
		
		<!-- Run the plugin -->
		<script type="text/javascript">
			$(window).load(function() {
				$('#featured').orbit();
			});
		</script>
</head>
<body>
<div id="tudo">
	
	<div id="header">
		<jsp:include page="cabecalho.jsp"></jsp:include>
	</div>
	
	<div id="content">
		<div id="esquerda">
			<jsp:include page="menu.jsp"></jsp:include>
			
			<a href="index.jsp?pag=cadastrarFalePrefeito"><img src="banners/falePrefeita.jpg" border="0" style="margin-top: 10px;" /></a>
		</div>		
		
		<div id="direita">
			<%--- Choose para escolher a página apropriada --%>		
			<c:choose>
				
				<c:when test='${empty param.pag}'>
					<jsp:include page="principal.jsp"></jsp:include>
				</c:when >
				
				<c:when test='${not empty param.pag}'>
					<jsp:include page="${param.pag}.jsp"></jsp:include>
				</c:when >					
				
				<c:otherwise>
					<h1>Nenhuma página selecionada</h1>
				</c:otherwise>				
			</c:choose >
		</div>

	</div>
	
	<div id="footer">
		<jsp:include page="rodape.jsp"></jsp:include>
	</div>

</div>
</body>
</html>

WebContent/noticiaExibe.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="noticia" class="model.Noticia" scope="request"></jsp:useBean>
	
	<h1>${noticia.not_titulo}</h1>
	<p>${noticia.dataHoraFormatada}</p>
	<p>&nbsp;</p>
	<p>${noticia.not_texto}</p>

WebContent/principal.jsp
<%@ taglib prefix="myTags" tagdir="/WEB-INF/tags/" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div id="principal">
	
	<div id="slider">
	
		<div class="contenter">
			<div id="featured"> 
				<div class="content" style="">
				</div>
		<jsp:useBean id="daoban" class="model.dao.DaoBanner" scope="request"></jsp:useBean>
		<c:forEach var="banner" items="${daoban.listBanHome}">
			<a href="http://${banner.ban_contato_site}" target="_blank"><img src="admin/exibirBanner.do?id=${banner.ban_id}" width="758" height="255" style="float: left;"/></a>
		</c:forEach>
			</div>
			
		</div>
		
	</div>
	
	
	
	<div id="noticias">	
		<jsp:useBean id="dao" class="model.dao.DaoNoticia" scope="request"></jsp:useBean>
		<c:forEach var="noticia" items="${dao.listNoticiasHome}">
			<div class="NoticiasBoxHome">
			<a href="noticiaExibe.do?not_id=${noticia.not_id}"><img src="admin/imagemNoticia.do?id=${noticia.not_id}" width="70" height="70" style="float: left; margin-right: 5px;"/>
			<p class="notTitulo">${noticia.not_titulo}</p>
			<p>${noticia.not_descricao}</p></a>
			</div>
		</c:forEach>	
	</div>
	
	<div id="intinerario">
		<a href="index.jsp?pag=transportes"><img src="banners/bannerOnibus.jpg" border="0" /></a>
	</div>
	
	<div id="eventos"><myTags:eventos></myTags:eventos></div>
	
	<div id="banners">
		<a href="http://www.transparencia.org.br/pindoretama"><img src="banners/banner_menor_1.jpg" width="175" height="75" border="0" /></a>
		<a href="http://www.ceara.ce.gov.br/diariooficial"><img src="banners/banner_menor_2.jpg" width="175" height="75" border="0" /></a>
		<a href="http://www.ceara.ce.gov.br"><img src="banners/banner_menor_3.jpg" width="175" height="74" border="0" /></a>
	</div>	

</div>

WebContent/rodape.jsp
<div id="rodape">
	<p>Sistema Web de Integração Municipal</p>
	<p>Todos os direitos reservados</p>
	<p><a href="admin/index.jsp">Administração</a></p>
</div>